---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	read_transcript(read_transcript)
	evaluate_abstain(evaluate_abstain)
	extract_updates(extract_updates)
	summarize_touch(summarize_touch)
	create_opportunity(create_opportunity)
	__end__([<p>__end__</p>]):::last
	__start__ --> read_transcript;
	evaluate_abstain -.-> extract_updates;
	evaluate_abstain -.-> summarize_touch;
	extract_updates --> summarize_touch;
	read_transcript --> evaluate_abstain;
	summarize_touch -.-> __end__;
	summarize_touch -.-> create_opportunity;
	create_opportunity --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
